/**
 * transform.ts — shape A to shape B, by modules walking hand over hand.
 *
 * Build (fitModules.ts) answers "what modules realise this shape, assembled from
 * nothing". This answers the harder question: the robot already EXISTS in one
 * shape, and must become another without ever coming apart.
 *
 * THE MOVE IS THE GAIT, NOT A TELEPORT
 * A module relocates the way the hardware actually can: it keeps one end welded,
 * folds, swings its free end onto some other module's connector, welds there, and
 * only then releases the end it was holding. So a module does not fly to its
 * destination — it WALKS the structure, connector to connector, and every
 * intermediate state is a real structure it was attached to the whole time.
 *
 * That makes relocation a path search over connectors.
 *
 * WHY A PER-MODULE GREEDY WALK IS NOT ENOUGH
 * An earlier version of this planner picked one module at a time and only ever
 * took a move that immediately covered more target cube — a pure hill-climb.
 * That stalls hard on any transformation that needs a module to shuffle onto a
 * cube that is NOT part of the final shape, purely to get out of another
 * module's way so THAT module can reach its own target. Real reconfiguration is
 * full of exactly this: parking, detours, "you go first". A planner that will
 * only ever take a locally-improving step cannot discover any of it, and comes
 * back with unreached cubes sitting right next to modules with legal moves
 * available — the moves just did not look like progress in isolation.
 *
 * HOW THIS ONE WORKS: BEAM SEARCH OVER WHOLE-ROBOT STATES
 * The unit of search is not "where does this module go" but "what is the whole
 * robot's configuration" — every module's anchor connector and facing at once.
 * From a state, a successor is generated by taking ANY one legal grab-release
 * move by ANY one module (oneStepMoves), whether or not that move covers a new
 * target cube. The best few states by coverage (ties broken by how close the
 * remaining modules sit to the remaining targets) are kept — a beam, not a
 * single line of descent — and expanded again, round after round. This is what
 * lets a plan pass through a state that is temporarily no better, or even worse,
 * than the one before it, on the way to one that is a lot better. That is the
 * capability a per-module greedy search structurally cannot have.
 *
 * It costs more to compute than the old greedy walk, and is bounded by a move
 * ceiling and an expansion ceiling rather than run to true exhaustion — for a
 * few dozen modules the state space is too large to search completely. What
 * comes back is the best state the beam actually reached, honestly reported as
 * partial if the beam ran out before reaching full coverage.
 *
 * HOW A PLAN IS PUT TOGETHER
 *   1. Fit the target shape, giving the placements the modules must end up in.
 *   2. Align the target onto the robot for maximum overlap — a module already
 *      sitting on a target cube counts immediately, for free.
 *   3. Beam-search from there, one whole-robot move at a time.
 *
 * MODULE COUNT: WALK FIRST, THEN RECONCILE
 * A target shape usually needs a different number of modules than the robot
 * has right now. The search only ever walks the modules that actually exist —
 * it never invents one mid-search, because a "move" that fabricates a module
 * is not a move any real gait can make. Once the search is done, if the count
 * still does not match, modules are explicitly added (placed per the target's
 * own build, not walked there — this is a deliberate capability, not a gait,
 * and is not claimed to be a modeled physical assembly step) or removed
 * (the surplus contributing least unique coverage first). Every add and
 * remove is named in the log — nothing about the module count changes
 * silently, whichever direction it moves.
 */
import { type Cell, key, manhattan, bestAlignment, translateCells } from './lattice';
import { type LatticePose } from './chainMoves';
import { findLandingPoses } from './chainSolve';
import {
  type FittedModule, type FitResult, type PlacedConnector,
  fitModules, connectorsOf, rotationTo, inverseRotationTo,
} from './fitModules';
import { type ConnectorEnd, weldTypeIsLegal, oppositeSideEnd } from './modulink';

const negCell = (c: Cell): Cell => [-c[0], -c[1], -c[2]];
const addCell = (a: Cell, b: Cell): Cell => [a[0] + b[0], a[1] + b[1], a[2] + b[2]];
const subCell = (a: Cell, b: Cell): Cell => [a[0] - b[0], a[1] - b[1], a[2] - b[2]];

/** One hand-over-hand step: grab with the free end, then let the other go. */
export interface TransformMove {
  index: number;
  moduleId: string;
  /** the connector that was holding, and is released once the grab is made */
  releaseEnd: 'A' | 'B';
  /** the connector that travels and welds */
  grabEnd: 'A' | 'B';
  /** where the module was anchored before the step */
  fromCell: Cell;
  fromDir: Cell;
  /** where it is anchored after */
  toCell: Cell;
  toDir: Cell;
  /** module and connector it grabbed */
  ontoModule: string;
  ontoEnd: ConnectorEnd;
  pose: LatticePose;
  /** body cubes after the step */
  cells: Cell[];
}

export interface TransformResult {
  moves: TransformMove[];
  /** the build the transformation is aiming at, for reference */
  targetBuild: FitResult;
  /** true only when every target cube ends up under a module */
  complete: boolean;
  /** target cubes covered when the plan ends */
  covered: number;
  /** target cubes in total */
  targetCubes: number;
  log: string[];
  /**
   * The robot's actual final module set: `current.modules` walked through
   * `moves`, then reconciled to the target's own module count by adding or
   * removing whole modules (see `reconcileModuleCount`). This is what a
   * complete plan's LAST frame should render — `structureAfter` alone only
   * knows about the walk, not the add/remove step, so it cannot produce this
   * on its own.
   */
  finalModules: FittedModule[];
  /** ids of modules that did not exist on the robot and were added */
  added: string[];
  /** ids of modules the robot had that were removed as surplus */
  removed: string[];
}

/**
 * The real weld graph, computed from geometry rather than trusted from the
 * `weldedTo` field — that field is a build-time record of ONE choice made
 * once, at construction, and is never updated as the search moves modules
 * around, so by the second move it is stale. Two connectors are actually
 * mated when they sit on the same lattice cell facing exactly opposite ways
 * — that is what a weld physically is, and it is true regardless of which
 * module the fitter happened to record as welding onto which.
 */
interface WeldState {
  /** module id -> ids of modules it is currently, physically welded to */
  neighbors: Map<string, Set<string>>;
  /** "moduleId:end" -> the far side's "moduleId:end" it is welded to */
  occupied: Map<string, string>;
}

function weldState(modules: FittedModule[]): WeldState {
  const byCell = new Map<string, { moduleId: string; end: ConnectorEnd; dir: Cell }[]>();
  for (const m of modules) {
    for (const c of connectorsOf(m)) {
      const k = key(c.cell);
      const list = byCell.get(k);
      const entry = { moduleId: m.id, end: c.end, dir: c.dir };
      if (list) list.push(entry); else byCell.set(k, [entry]);
    }
  }
  const neighbors = new Map<string, Set<string>>(modules.map((m) => [m.id, new Set<string>()]));
  const occupied = new Map<string, string>();
  for (const entries of byCell.values()) {
    for (let i = 0; i < entries.length; i++) {
      for (let j = i + 1; j < entries.length; j++) {
        const a = entries[i]; const b = entries[j];
        if (a.moduleId === b.moduleId) continue;
        // Mated: opposite-facing normals at the same cell. Same-facing would
        // mean two connectors merely occupying the same cell, not locked
        // together — geometrically shouldn't happen for legal poses, but
        // checked rather than assumed.
        if (a.dir[0] !== -b.dir[0] || a.dir[1] !== -b.dir[1] || a.dir[2] !== -b.dir[2]) continue;
        neighbors.get(a.moduleId)!.add(b.moduleId);
        neighbors.get(b.moduleId)!.add(a.moduleId);
        occupied.set(`${a.moduleId}:${a.end}`, `${b.moduleId}:${b.end}`);
        occupied.set(`${b.moduleId}:${b.end}`, `${a.moduleId}:${a.end}`);
      }
    }
  }
  return { neighbors, occupied };
}

/**
 * Would `others` still be ONE connected piece with `moving` gone entirely?
 * If not, `moving` is a bridge — the only thing holding two halves of the
 * robot together — and it cannot detach as a single hand-over-hand step
 * without the structure coming apart, whatever else about the move looks
 * legal. This is the actual "never comes apart" guarantee the header comment
 * promises; nothing enforced it before this check existed.
 */
function staysConnectedWithout(moving: FittedModule, others: FittedModule[]): boolean {
  if (others.length <= 1) return true;
  const { neighbors } = weldState(others);
  const seen = new Set<string>([others[0].id]);
  const queue = [others[0].id];
  while (queue.length) {
    const cur = queue.shift() as string;
    for (const n of neighbors.get(cur) ?? []) {
      if (!seen.has(n)) { seen.add(n); queue.push(n); }
    }
  }
  return seen.size === others.length;
}

/** A connector another module could grab, with its side-face budget. */
interface GrabTarget extends PlacedConnector {
  usedSides: ConnectorEnd[];
}

function grabTargets(modules: FittedModule[], exclude: string): GrabTarget[] {
  // Which side connectors are ALREADY welded, from real geometry — a target
  // module's own occupied side faces must count against the "at most two,
  // opposite" budget even though this list only ever contains OTHER modules'
  // connectors; the occupancy comes from the whole structure, not just what
  // is being offered as a target.
  const { occupied } = weldState(modules);
  const usedSidesOf = (moduleId: string): ConnectorEnd[] => {
    const ends: ConnectorEnd[] = ['A', 'B', 'UP', 'DOWN', 'LEFT', 'RIGHT'];
    return ends.filter((e) => e !== 'A' && e !== 'B' && occupied.has(`${moduleId}:${e}`));
  };

  const out: GrabTarget[] = [];
  for (const m of modules) {
    if (m.id === exclude) continue;
    const usedSides = usedSidesOf(m.id);
    for (const c of connectorsOf(m)) {
      out.push({ ...c, usedSides });
    }
  }
  return out;
}

/** Can a travelling end weld onto this connector? */
function grabbable(grabEnd: ConnectorEnd, t: GrabTarget): boolean {
  if (!weldTypeIsLegal(grabEnd, t.end)) return false;
  if (t.end === 'A' || t.end === 'B') return true;
  // Side faces: at most two, and they must be opposite.
  if (t.usedSides.length >= 2) return false;
  return t.usedSides.every((u) => u === t.end || oppositeSideEnd(u) === t.end);
}

/**
 * Walk one module AS CLOSE AS IT CAN GET to where it needs to be, hand over hand.
 *
 * Every legal grab-then-release move `m` could make right now, against a static
 * `others`. Deliberately does NOT filter by whether the move helps — that
 * judgement belongs to the search that calls this, not to the move generator.
 * One candidate move per reachable connector site (the first collision-free
 * route to it), which keeps branching bounded to roughly "how many places can
 * this module's free end land", the same count mobilityReport measures.
 */
export function oneStepMoves(m: FittedModule, others: FittedModule[]): TransformMove[] {
  // SAFETY GATE, CHECKED FIRST: if `m` is currently the only thing holding
  // two halves of the structure together, it cannot detach at all — not "it
  // has fewer options", it has NONE, full stop. A single hand-over-hand step
  // physically cannot relocate a bridge module without splitting the robot
  // at the instant it lets go, no matter how good the destination is. See
  // staysConnectedWithout's own comment for why this is computed from real
  // geometry rather than trusted from build-time bookkeeping.
  if (!staysConnectedWithout(m, others)) return [];

  const targets = grabTargets(others, m.id);
  const blocked = new Set<string>();
  for (const o of others) for (const c of o.cells) blocked.add(key(c));

  const rot = rotationTo(m.anchorDir);
  const invRot = inverseRotationTo(m.anchorDir);
  const out: TransformMove[] = [];
  const seenTarget = new Set<string>();

  for (const t of targets) {
    if (!grabbable('B', t)) continue;
    const sk = key(t.cell) + '|' + key(t.dir);
    if (seenTarget.has(sk)) continue;
    seenTarget.add(sk);

    const wantedOffset = invRot(subCell(t.cell, m.anchorCell));
    const wantedDir = invRot(negCell(t.dir));

    // Requesting fewer alternates than the default (4) here: this loop only
    // ever uses the FIRST collision-free one (the `break` below) — it is not
    // the caller that benefits from a deep alternates list, mobilityReport is
    // (see its own call, which keeps the default). Each extra alternate the
    // solver is asked for costs a real LM solve over more seeds, and this is
    // the innermost loop of the whole search: called for every candidate
    // connector of every module of every beam node, every round. Measured
    // cost per module here was 60-600ms with the default; 2 alternates still
    // keeps ONE spare route for a body-collision fallback (the whole reason
    // alternates exist at all — see chainSolve.ts) while cutting well below
    // that.
    for (const pose of findLandingPoses(wantedOffset, wantedDir, undefined, 2)) {
      const endCell = t.cell;
      const endDir = negCell(t.dir);
      // Body must clear the static structure. It may share the cube it anchors
      // in and the cube it is grabbing — those are welds, not collisions.
      const cells = pose.cells.map((c) => addCell(m.anchorCell, rot(c)));
      const hits = cells.some((c) => {
        const k = key(c);
        return k !== key(m.anchorCell) && k !== key(endCell) && blocked.has(k);
      });
      if (hits) continue; // this route is blocked; try the next one

      out.push({
        index: 0,
        moduleId: m.id,
        releaseEnd: 'A',
        grabEnd: 'B',
        fromCell: m.anchorCell,
        fromDir: m.anchorDir,
        toCell: endCell,
        toDir: endDir,
        ontoModule: t.moduleId,
        ontoEnd: t.end,
        pose,
        cells,
      });
      break; // one working route to this site is enough as a candidate move
    }
  }
  return out;
}

// ── beam search over whole-robot states ─────────────────────────────────────

interface SearchNode {
  modules: FittedModule[];
  moves: TransformMove[];
  coverage: number;
}

/** Identifies a whole-robot configuration by every module's held connector and
 *  facing — two states with this in common are the same state for search
 *  purposes, whatever route was taken to reach them. */
const stateSignature = (modules: FittedModule[]): string =>
  modules.map((m) => `${m.id}:${key(m.anchorCell)}|${key(m.anchorDir)}`).sort().join(',');

const coverageOf = (modules: FittedModule[], targetCells: Set<string>): number => {
  const s = new Set<string>();
  for (const m of modules) for (const c of m.cells) if (targetCells.has(key(c))) s.add(key(c));
  return s.size;
};

/**
 * Tie-breaker only: how far the still-uncovered target cubes are from the
 * nearest module, summed. Two states can cover the same number of target
 * cubes while one has everything else parked right next to the remaining gaps
 * and the other has it on the far side of the robot — the first is worth
 * exploring further, the second is not, and coverage alone cannot tell them
 * apart. This is what keeps the beam pointed at progress instead of wandering
 * the plateau that non-improving moves open up.
 */
function distanceToGo(modules: FittedModule[], targetCells: Set<string>, targetCellList: Map<string, Cell>): number {
  const covered = new Set<string>();
  for (const m of modules) for (const c of m.cells) if (targetCells.has(key(c))) covered.add(key(c));
  let total = 0;
  for (const [k, cell] of targetCellList) {
    if (covered.has(k)) continue;
    let best = Infinity;
    for (const m of modules) {
      const d = manhattan(m.anchorCell, cell);
      if (d < best) best = d;
    }
    total += best;
  }
  return total;
}

export interface TransformOptions {
  /** how many whole-robot states the search keeps and expands each round */
  beamWidth: number;
  /** hard ceiling on plan length, and on search depth */
  maxMoves: number;
  /** safety cap on total states expanded, independent of maxMoves */
  maxExpansions: number;
  /** REAL COMPUTE-TIME budget in ms — time spent yielded back to the UI
   *  between chunks does not count against it, only actual search work does.
   *  The search stops and returns its best state so far once this elapses,
   *  whether or not the expansion cap was reached. An incomplete transform is
   *  the common case (see the module header), so without this bound every
   *  incomplete result would search until the expansion cap regardless of how
   *  long that takes. Because it excludes yield time, total wall-clock time
   *  can run somewhat longer than this number. */
  maxMs: number;
}

export const DEFAULT_TRANSFORM_OPTIONS: TransformOptions = {
  beamWidth: 8,
  maxMoves: 150,
  maxExpansions: 20000,
  maxMs: 4000,
};

/** A snapshot of what the search is doing right now, for a UI to render. */
export interface SearchProgress {
  round: number;
  expansions: number;
  /** best coverage found so far, and the target it is working toward */
  coverage: number;
  targetCubes: number;
  elapsedMs: number;
  budgetMs: number;
  /** the module whose moves are being enumerated at this instant, if mid-node */
  moduleId: string | null;
  moduleIndex: number;
  moduleCount: number;
  /** how many whole-robot states are being carried into the next round */
  beamSize: number;
}

/** Hands control back to the event loop for one paint, so progress callbacks
 *  fired just before this actually reach the screen instead of queuing up
 *  behind a still-blocking synchronous search. */
const yieldToUI = (): Promise<void> => new Promise((resolve) => {
  if (typeof requestAnimationFrame === 'function') requestAnimationFrame(() => resolve());
  else setTimeout(resolve, 0);
});

/**
 * Beam search from `start` toward maximum coverage of `targetCells`. Returns
 * the best (highest-coverage, then fewest-moves) state actually reached — not
 * necessarily a complete one. `others` outside the robot never enter into
 * this; every module in `start.modules` is part of the search.
 *
 * ASYNC ON PURPOSE. Each module's move enumeration runs real IK solves and can
 * take on the order of 100ms; run straight through, a multi-second search is a
 * multi-second UI freeze with a spinning CPU and nothing on screen explaining
 * why. Periodically (roughly every 60ms of work) this reports a SearchProgress
 * snapshot and yields one animation frame so the caller's state update and the
 * browser's paint actually happen before the search resumes — a synchronous
 * function cannot do this at all, no matter how often it is "called"; nothing
 * yields the thread back until it returns.
 */
async function beamSearchTransform(
  start: FittedModule[],
  targetCells: Set<string>,
  targetCellList: Map<string, Cell>,
  opts: TransformOptions,
  onProgress?: (p: SearchProgress) => void,
): Promise<{ best: SearchNode; expansions: number; rounds: number; timedOut: boolean }> {
  let beam: SearchNode[] = [{ modules: start, moves: [], coverage: coverageOf(start, targetCells) }];
  const visited = new Set<string>([stateSignature(start)]);
  let best = beam[0];
  let expansions = 0;
  let round = 0;
  const searchStart = performance.now();
  let timedOut = false;

  // REAL COMPUTE TIME, NOT WALL-CLOCK TIME. `yieldToUI` hands control back to
  // the browser so the progress bar can repaint — and that pause takes real
  // time (a frame, more if anything else is going on), which is not the
  // search "thinking". A wall-clock deadline charges that pause against the
  // same budget as the search itself, so adding progress reporting silently
  // shrinks how much actual searching happens in a fixed wall-clock window —
  // measured regression: a structure that used to produce a real partial plan
  // came back with zero moves purely because yielding had eaten the budget.
  // `computeMs` only accumulates time between yields, so the search always
  // gets its full intended budget of real work; total wall-clock time is
  // whatever that plus the yields costs, which is allowed to be longer.
  let computeMs = 0;
  let chunkStart = searchStart;
  const overBudget = () => computeMs + (performance.now() - chunkStart) >= opts.maxMs;

  let lastYield = performance.now();

  const score = (n: SearchNode) => n.coverage * 100000 - distanceToGo(n.modules, targetCells, targetCellList) * 10 - n.moves.length;

  const report = (moduleId: string | null, moduleIndex: number, moduleCount: number) => {
    onProgress?.({
      round, expansions, coverage: best.coverage, targetCubes: targetCells.size,
      elapsedMs: computeMs + (performance.now() - chunkStart), budgetMs: opts.maxMs,
      moduleId, moduleIndex, moduleCount, beamSize: beam.length,
    });
  };

  // An incomplete transform is common (see the module header) and, without a
  // budget, that means "search until the expansion cap" on every single
  // incomplete result — the expansion cap alone does not protect interactive
  // use from a structure where that cap is expensive to reach.
  //
  // Checked at the START of every node's expansion, not just once per round:
  // one round can itself run over budget, because the real cost here is not
  // the search bookkeeping but the IK solves inside oneStepMoves (up to
  // modules × connectors of them, per node) — a single round measured at over
  // 6 seconds against a 4-second budget before this was tightened. A node
  // boundary is frequent enough that the overrun past the budget stays small.
  outer: while (beam.length && best.coverage < targetCells.size) {
    const successors: SearchNode[] = [];

    for (const node of beam) {
      if (overBudget()) { timedOut = true; break outer; }
      if (node.moves.length >= opts.maxMoves) continue;

      for (let i = 0; i < node.modules.length; i++) {
        // Also checked mid-node: on a large structure the per-module IK-solve
        // loop below can by itself exceed the whole budget before the node
        // finishes, so this is the tightest granularity worth the cost of a
        // performance.now() call.
        if (overBudget()) { timedOut = true; break outer; }
        const m = node.modules[i];
        const others = node.modules.filter((x) => x.id !== m.id);

        if (performance.now() - lastYield > 60) {
          report(m.id, i, node.modules.length);
          computeMs += performance.now() - chunkStart;
          await yieldToUI();
          chunkStart = performance.now();
          lastYield = chunkStart;
        }

        const moves = oneStepMoves(m, others);

        for (const mv of moves) {
          const nextModules = node.modules.slice();
          nextModules[i] = { ...m, anchorCell: mv.toCell, anchorDir: mv.toDir, cells: mv.cells, pose: mv.pose };
          const sig = stateSignature(nextModules);
          if (visited.has(sig)) continue;
          visited.add(sig);

          const nextMove: TransformMove = { ...mv, index: node.moves.length };
          const next: SearchNode = {
            modules: nextModules,
            moves: [...node.moves, nextMove],
            coverage: coverageOf(nextModules, targetCells),
          };
          successors.push(next);
          if (next.coverage > best.coverage
            || (next.coverage === best.coverage && next.moves.length < best.moves.length)) {
            best = next;
          }
          expansions++;
        }
        if (expansions >= opts.maxExpansions) break;
      }
      if (expansions >= opts.maxExpansions) break;
    }

    if (!successors.length || expansions >= opts.maxExpansions) break;

    successors.sort((a, b) => score(b) - score(a));
    beam = successors.slice(0, opts.beamWidth);
    round++;
    report(null, 0, 0);
  }

  report(null, 0, 0);
  return { best, expansions, rounds: round, timedOut };
}

// ── module-count reconciliation ───────────────────────────────────────────────

/**
 * After walking, make the module count exactly match the target's own build.
 *
 * ADDING: greedy set cover — repeatedly take whichever of the target's own
 * modules still covers the most cells nobody kept has covered yet, until
 * either the deficit is filled or nothing left helps. Placed exactly where
 * the target's own fit put it (both are already in the same, aligned, cell
 * frame — see planTransform), not solved as a walk from anywhere, because
 * there is no existing connector on the robot for a module that does not
 * exist yet to have walked from.
 *
 * REMOVING: repeatedly drop whichever surviving module contributes the
 * FEWEST target cells that no other surviving module also covers — recomputed
 * after each removal, since taking one out can make a previously-redundant
 * module load-bearing. This is the same "does not disturb what does not need
 * to move" instinct as the search's alignment step, applied to deletion.
 */
/**
 * Does any connector of `candidate` mate with any connector of `existing`? A
 * plain geometric coincidence check (same cell, opposite facing), not keyed
 * by module id — `candidate` typically comes from a DIFFERENT FitResult than
 * `existing` (the target's own build vs. the walked robot), so ids can and
 * do collide between them; `weldState`'s id-keyed map is not safe to reuse
 * here for that reason.
 */
function connectsToAny(candidate: FittedModule, existing: FittedModule[]): boolean {
  if (existing.length === 0) return true; // nothing to connect to yet
  for (const m of existing) {
    for (const c of connectorsOf(m)) {
      for (const cc of connectorsOf(candidate)) {
        if (key(cc.cell) === key(c.cell)
          && cc.dir[0] === -c.dir[0] && cc.dir[1] === -c.dir[1] && cc.dir[2] === -c.dir[2]) {
          return true;
        }
      }
    }
  }
  return false;
}

function reconcileModuleCount(
  walked: FittedModule[],
  targetBuild: FitResult,
  targetCells: Set<string>,
  log: string[],
): { finalModules: FittedModule[]; added: string[]; removed: string[] } {
  let modules = walked.map((m) => ({ ...m }));
  const added: string[] = [];
  const removed: string[] = [];
  let addedDisconnected = 0;

  if (modules.length < targetBuild.modules.length) {
    const covered = new Set<string>();
    for (const m of modules) for (const c of m.cells) covered.add(key(c));
    const stillMissing = new Set([...targetCells].filter((k) => !covered.has(k)));

    const deficit = targetBuild.modules.length - modules.length;
    const pool = [...targetBuild.modules];
    while (added.length < deficit && pool.length) {
      // Coverage gain is the primary signal, but a candidate that actually
      // WELDS onto what exists so far is strongly preferred over one that
      // would just float nearby — a floating module is exactly the "reaches
      // the shape" plan that renders as a scattered mess with a piece
      // hanging in empty space, which coverage math alone cannot see.
      let bestIdx = -1;
      let bestScore = -Infinity;
      pool.forEach((c, i) => {
        const gain = c.cells.filter((cell) => stillMissing.has(key(cell))).length;
        const connects = connectsToAny(c, modules);
        const score = gain + (connects ? 1000 : 0);
        if (score > bestScore) { bestScore = score; bestIdx = i; }
      });
      const chosen = pool.splice(bestIdx, 1)[0];
      const willConnect = connectsToAny(chosen, modules);
      if (!willConnect) addedDisconnected++;
      const newId = `A${added.length}-${chosen.id}`;
      const placed: FittedModule = { ...chosen, id: newId, weldedTo: null };
      modules = [...modules, placed];
      for (const c of placed.cells) stillMissing.delete(key(c));
      added.push(newId);
    }
    log.push(
      `added ${added.length} module(s) the robot did not have (${added.join(', ')}): placed per the `
      + 'target build directly, not walked there — the walk above is what the existing modules can '
      + 'physically reach; this is a separate, explicit "add hardware" step.',
    );
    if (addedDisconnected > 0) {
      log.push(
        `WARNING: ${addedDisconnected} of those added module(s) do not weld onto anything else in the `
        + 'final structure — no candidate in the target build reached far enough to connect. The shape '
        + 'is covered but the robot would be in pieces; this is reported, not hidden.',
      );
    }
  }

  if (modules.length > targetBuild.modules.length) {
    const surplus = modules.length - targetBuild.modules.length;
    let removedBridge = 0;
    for (let i = 0; i < surplus && modules.length > 0; i++) {
      const coverageCount = new Map<string, number>();
      for (const m of modules) for (const c of m.cells) {
        const k = key(c);
        if (!targetCells.has(k)) continue;
        coverageCount.set(k, (coverageCount.get(k) ?? 0) + 1);
      }
      // Rank candidates by unique coverage contribution (lowest first), but
      // walk down that ranking to the first one that does NOT fragment the
      // rest of the structure — removing a bridge module is just as much a
      // "comes apart" failure as walking one away would be.
      const ranked = modules
        .map((m, idx) => ({
          idx,
          unique: m.cells.filter((c) => targetCells.has(key(c)) && coverageCount.get(key(c)) === 1).length,
        }))
        .sort((a, b) => a.unique - b.unique);

      let pickIdx = ranked[0]?.idx ?? 0;
      let safe = false;
      for (const r of ranked) {
        const candidate = modules[r.idx];
        const rest = modules.filter((_, idx) => idx !== r.idx);
        if (staysConnectedWithout(candidate, rest)) { pickIdx = r.idx; safe = true; break; }
      }
      if (!safe) removedBridge++;

      const gone = modules.splice(pickIdx, 1)[0];
      removed.push(gone.id);
    }
    log.push(`removed ${removed.length} surplus module(s) not needed for this shape (${removed.join(', ')})`);
    if (removedBridge > 0) {
      log.push(
        `WARNING: ${removedBridge} removal(s) had no safe (non-fragmenting) candidate available and `
        + 'removed the least-load-bearing one anyway — the final structure may be in more than one piece.',
      );
    }
  }

  return { finalModules: modules, added, removed };
}

/**
 * Plan a transformation from a built robot into a target shape.
 *
 * `current` must be the result of Build on the shape the robot is in now.
 */
export async function planTransform(
  current: FitResult,
  targetShape: Cell[],
  options: Partial<TransformOptions> = {},
  onProgress?: (p: SearchProgress) => void,
): Promise<TransformResult> {
  const opts = { ...DEFAULT_TRANSFORM_OPTIONS, ...options };
  const log: string[] = [];
  const t0 = performance.now();

  // ALIGN THE TARGET ONTO THE ROBOT FIRST — before fitting it into modules at
  // all, so the modules that come out of that fit already live in the SAME
  // cell frame as the robot, and can be spliced straight onto it later if the
  // module count needs to grow (see reconcileModuleCount). Fitting the raw,
  // ground-centred target first and aligning afterward would leave its
  // modules positioned in the wrong frame entirely.
  //
  // A robot cannot teleport across the grid: a module only ever relocates onto
  // a connector of its own structure, so anything outside the structure's own
  // reach is unreachable no matter how good the planner is. Both shapes come
  // out of the library ground-centred, which is NOT the same as overlapping —
  // a snake and a bridge of the same cube count landed with ZERO cubes in
  // common, and the plan was correctly but uselessly empty because there was
  // nothing within reach to move toward.
  //
  // So the target is translated to sit where it overlaps the robot most,
  // exactly as the cube planner does (planReconfiguration/bestAlignment). This
  // is not a trick to inflate the numbers: a target shape is a SHAPE, not a
  // location, and choosing where to build it is part of the problem. Every
  // module already in the right place then stays put, which is where most of
  // the saving comes from.
  const bodyCells: Cell[] = [];
  for (const m of current.modules) bodyCells.push(...m.cells);
  const shift: Cell = bodyCells.length ? bestAlignment(bodyCells, targetShape) : [0, 0, 0];
  const alignedTarget = translateCells(targetShape, shift);
  if (shift[0] || shift[1] || shift[2]) {
    log.push(`target aligned onto the robot by (${shift.join(',')}) for maximum overlap`);
  }

  const targetBuild = fitModules(alignedTarget);
  log.push(
    `target shape of ${targetShape.length} cubes needs ${targetBuild.modules.length} modules; `
    + `you have ${current.modules.length}`,
  );

  if (!targetBuild.modules.length) {
    log.push('the target shape could not be built at all — nothing to transform into');
    return {
      moves: [], targetBuild, complete: false, covered: 0, targetCubes: targetShape.length, log,
      finalModules: current.modules, added: [], removed: [],
    };
  }

  if (targetBuild.modules.length !== current.modules.length) {
    log.push(
      `module count differs (${current.modules.length} now, ${targetBuild.modules.length} wanted) — `
      + 'the robot walks what it already has as far as that can go, then the count is reconciled by '
      + 'adding or removing whole modules to close the gap exactly (reported below, not silent).',
    );
  }

  // The goal is COVERAGE of that target, not each module reaching an assigned
  // slot. Slot matching is brittle here: a module's assigned placement is usually
  // not a valid connector site until its neighbours have moved, so matching
  // strands everything. What matters is that the modules occupy the target shape.
  const targetCells = new Set(alignedTarget.map(key));
  const targetCellList = new Map(alignedTarget.map((c) => [key(c), c] as const));

  const startCovered = coverageOf(current.modules, targetCells);
  log.push(`${startCovered} of ${targetCells.size} target cubes are already covered`);

  // If nothing can move at all, say so plainly instead of returning an empty plan
  // that looks like a planner failure.
  const mob = mobilityReport(current);
  log.push(`mobility: ${mob.summary}`);

  const searchStart = performance.now();
  const { best, expansions, rounds, timedOut } = await beamSearchTransform(
    current.modules.map((m) => ({ ...m })), targetCells, targetCellList, opts, onProgress,
  );
  const moves = best.moves;
  log.push(
    `beam search: ${expansions} state(s) expanded over ${rounds} round(s) `
    + `(beam width ${opts.beamWidth}) in ${(performance.now() - searchStart).toFixed(0)}ms `
    + `search time (${(performance.now() - t0).toFixed(0)}ms total including target-fit and mobility scan)`
    + (timedOut ? ` — stopped at the ${opts.maxMs}ms search budget, not exhausted` : ''),
  );

  const walkedCovered = best.coverage;
  log.push(`walking covered ${startCovered} → ${walkedCovered} of ${targetCells.size} target cubes`);
  if (walkedCovered < targetCells.size) {
    log.push(
      `${targetCells.size - walkedCovered} target cube(s) not reached by walking within the search budget `
      + `(${opts.maxExpansions} expansions, ${opts.maxMs}ms, beam width ${opts.beamWidth}) — closed below `
      + 'by adding modules instead, since walking alone did not get there.',
    );
  }
  if (moves.length >= opts.maxMoves) log.push(`hit the ${opts.maxMoves}-move ceiling`);

  const { finalModules, added, removed } = reconcileModuleCount(best.modules, targetBuild, targetCells, log);
  const endCovered = coverageOf(finalModules, targetCells);
  const complete = endCovered === targetCells.size;
  log.push(
    `final: ${endCovered} of ${targetCells.size} target cubes, ${finalModules.length} module(s)`
    + `${complete ? ' — complete' : ''}`,
  );

  return {
    moves,
    targetBuild,
    complete,
    covered: endCovered,
    targetCubes: targetCells.size,
    log,
    finalModules,
    added,
    removed,
  };
}

// ── mobility diagnostic ───────────────────────────────────────────────────────

export interface ModuleMobility {
  moduleId: string;
  /** distinct anchor states one grab-and-release can reach */
  reachable: number;
  /** poses that land on a connector but whose body is blocked */
  blockedByBody: number;
  /** poses that land on a cube holding a connector, but facing the wrong way */
  wrongFacing: number;
  /**
   * True when this module is currently the only thing holding two halves of
   * the structure together — detaching it would split the robot, so it has
   * ZERO legal moves regardless of what targets exist. A different failure
   * mode than the other three: those say "nowhere good to land", this says
   * "cannot even let go".
   */
  bridge: boolean;
}

export interface MobilityReport {
  perModule: ModuleMobility[];
  total: number;
  frozen: number;
  summary: string;
}

/**
 * How much can each module actually move, right now, in one step?
 *
 * This exists because an empty transformation plan is otherwise indistinguishable
 * from a broken planner, and it is usually neither: it is a robot that is packed
 * too tightly to rearrange. A module can only relocate by landing its free end
 * EXACTLY on an existing connector while its body clears everything else, and in
 * a compact structure there are few such places. Knowing which of the two
 * filters is doing the rejecting is what tells you whether to loosen the shape
 * or fix the model.
 *
 * QUERIES BY TARGET, AND TRIES EVERY ROUTE TO EACH
 * Iterating the real connectors (a handful) rather than the whole reach table
 * (hundreds of poses) is the natural direction: each connector implies exactly
 * one (offset, facing) the module must hit, and findLandingPoses answers that
 * from the table when it can and the solver when it cannot.
 *
 * The critical detail is that it asks for ALL routes to each connector and only
 * counts the target unreachable once EVERY route collides. An earlier revision
 * took the first route and gave up if it collided, which made mobility go DOWN
 * when the solver was wired in — the solver returned one geometrically valid
 * route where the table had been quietly offering several. Alternates are the
 * whole reason this is a gain rather than a regression.
 */
export function mobilityReport(build: FitResult): MobilityReport {
  const perModule: ModuleMobility[] = [];

  for (const m of build.modules) {
    const others = build.modules.filter((x) => x.id !== m.id);

    // Checked before anything else, matching oneStepMoves: a bridge module
    // has zero legal moves no matter what targets exist, because letting go
    // at all splits the robot. Reporting it as "0 reachable, 0 blocked, 0
    // wrong-facing" would look like a bug-free module that simply has no
    // options; `bridge: true` says the real reason instead.
    if (!staysConnectedWithout(m, others)) {
      perModule.push({ moduleId: m.id, reachable: 0, blockedByBody: 0, wrongFacing: 0, bridge: true });
      continue;
    }

    const targets = grabTargets(others, m.id);
    const blocked = new Set<string>();
    for (const o of others) for (const c of o.cells) blocked.add(key(c));

    const rot = rotationTo(m.anchorDir);
    const invRot = inverseRotationTo(m.anchorDir);
    let reachable = 0, blockedByBody = 0, wrongFacing = 0;
    const seen = new Set<string>();

    for (const t of targets) {
      if (!grabbable('B', t)) continue;
      const wantedOffset = invRot(subCell(t.cell, m.anchorCell));
      const wantedDir = invRot(negCell(t.dir));
      const sk = `${key(wantedOffset)}|${key(wantedDir)}`;
      if (seen.has(sk)) continue;
      seen.add(sk);

      const routes = findLandingPoses(wantedOffset, wantedDir);
      if (!routes.length) { wrongFacing++; continue; } // no fold reaches it at all

      // Reachable if ANY route gets there without the body hitting something.
      let cleared = false;
      for (const pose of routes) {
        const endCell = addCell(m.anchorCell, rot(pose.endOffset));
        const cells = pose.cells.map((c) => addCell(m.anchorCell, rot(c)));
        const hits = cells.some((c) => {
          const k = key(c);
          return k !== key(m.anchorCell) && k !== key(endCell) && blocked.has(k);
        });
        if (!hits) { cleared = true; break; }
      }
      if (cleared) reachable++;
      else blockedByBody++;
    }
    perModule.push({ moduleId: m.id, reachable, blockedByBody, wrongFacing, bridge: false });
  }

  const total = perModule.reduce((n, p) => n + p.reachable, 0);
  const frozen = perModule.filter((p) => p.reachable === 0).length;
  const bridged = perModule.filter((p) => p.bridge).length;
  return {
    perModule,
    total,
    frozen,
    summary: total === 0
      ? 'every module is frozen — no free end can reach another connector without the body '
        + 'hitting something, or it would split the robot to let go at all. '
        + 'Nothing can be rearranged from this configuration.'
      : `${total} single-step relocation(s) available across ${build.modules.length} modules; `
        + `${frozen} module(s) frozen`
        + (bridged ? ` (${bridged} of those because moving would split the structure in two)` : ''),
  };
}

/** Module bodies after the first `count` steps of a plan — for scrubbing playback. */
export function structureAfter(current: FitResult, moves: TransformMove[], count: number): FittedModule[] {
  const live = new Map(current.modules.map((m) => [m.id, { ...m }]));
  for (let i = 0; i < Math.min(count, moves.length); i++) {
    const mv = moves[i];
    const m = live.get(mv.moduleId);
    if (!m) continue;

    // DRAW anchor, not the planner's held-connector state. `mv.pose` was solved
    // relative to the connector the module held DURING the move — mv.fromCell —
    // so that is the only anchor it can be drawn from. Pairing mv.pose with
    // mv.toCell (where the free end landed, and what the module holds NEXT)
    // describes no real configuration and renders the module in the wrong place
    // entirely. The two coordinates are both correct and mean different things:
    // fromCell is where the body hangs from, toCell is what it is now gripping.
    m.anchorCell = mv.fromCell;
    m.anchorDir = mv.fromDir;
    m.cells = mv.cells;
    m.pose = mv.pose;
  }
  return [...live.values()];
}

/** One-line description of a step, for the plan list and the hardware log. */
export function describeTransformMove(mv: TransformMove): string {
  return `${mv.index + 1}. ${mv.moduleId}: hold ${mv.releaseEnd === 'A' ? 'B' : 'A'}, fold to `
    + `${mv.pose.bendPoseId}, grab ${mv.ontoModule}.${mv.ontoEnd} at (${mv.toCell.join(',')}), `
    + `release ${mv.releaseEnd}`;
}
