/**
 * mjcf.ts — export the model graph to MJCF (MuJoCo's XML format).
 *
 * MJCF is a NESTED kinematic tree: each body element contains its child bodies, with
 * the joint declared inside the child. We build the parent→children map from the graph
 * (first joint per child = parent), then recurse from each root. Geometry → <geom>,
 * joints → <joint>. Node-testable (no three needed; pure string assembly).
 */
import type { Document } from '@/core/model/index';

const san = (s: any) => String(s ?? 'x').replace(/[^A-Za-z0-9_]/g, '_');
const n = (v: any) => (Math.abs(v) < 1e-9 ? '0' : (+v).toFixed(6));
const v3 = (p: any) => `${n((p ?? [0, 0, 0])[0])} ${n((p ?? [0, 0, 0])[1])} ${n((p ?? [0, 0, 0])[2])}`;
const quat = (q: any) => { const a = q ?? [0, 0, 0, 1]; return `${n(a[3])} ${n(a[0])} ${n(a[1])} ${n(a[2])}`; }; // MuJoCo is w x y z

function geomXML(g: any) {
  switch (g?.type) {
    case 'box': { const s = g.size ?? [1, 1, 1]; return `<geom type="box" size="${n(s[0] / 2)} ${n(s[1] / 2)} ${n(s[2] / 2)}"/>`; }
    case 'sphere': return `<geom type="sphere" size="${n(g.radius ?? 0.5)}"/>`;
    case 'cylinder': return `<geom type="cylinder" size="${n(g.radius ?? 0.5)} ${n((g.length ?? 1) / 2)}"/>`;
    case 'capsule': return `<geom type="capsule" size="${n(g.radius ?? 0.5)} ${n((g.length ?? 1) / 2)}"/>`;
    case 'mesh': return `<geom type="mesh" mesh="${san(g.assetId ?? 'mesh')}"/>`;
    default: return `<geom type="box" size="0.05 0.05 0.05"/>`;
  }
}

function jointXML(j: any) {
  if (!j) return '';
  if (j.type === 'fixed') return '';
  const type = j.type === 'prismatic' ? 'slide' : 'hinge';
  const ax = j.axis ?? [0, 0, 1];
  const lim = j.limit ?? {};
  const ranged = (j.type === 'revolute' || j.type === 'prismatic')
    ? ` limited="true" range="${n(lim.lower ?? -3.14)} ${n(lim.upper ?? 3.14)}"` : '';
  const o = j.origin ?? {};
  return `<joint name="${san(j.name)}" type="${type}" pos="${v3(o.position)}" axis="${n(ax[0])} ${n(ax[1])} ${n(ax[2])}"${ranged}/>`;
}

export function exportMJCF(doc: Document, name = 'tetrobot') {
  const allJoints = Object.values(doc.joints);
  const childParent = new Map<string, any>();      // childId -> joint
  const children = new Map<string, string[]>();     // parentId -> [childId]
  for (const j of allJoints) {
    const pid = (j as any).parentBodyId, cid = (j as any).childBodyId;
    if (!pid || !cid || !doc.bodies[pid] || !doc.bodies[cid] || childParent.has(cid)) continue;
    childParent.set(cid, j);
    if (!children.has(pid)) children.set(pid, []);
    children.get(pid)!.push(cid);
  }
  const roots = Object.values(doc.bodies).filter((b) => !childParent.has(b.id));

  const seen = new Set<string>();
  const bodyXML = (id: string, depth: number): string => {
    if (seen.has(id)) return '';
    seen.add(id);
    const b: any = doc.bodies[id];
    const pad = '  '.repeat(depth + 3);
    const j = childParent.get(id);
    const t = b.transform ?? {};
    const pos = j?.origin?.position ?? t.position ?? [0, 0, 0];
    const q = j?.origin?.quaternion ?? t.quaternion ?? [0, 0, 0, 1];
    const kids = (children.get(id) ?? []).map((cid) => bodyXML(cid, depth + 1)).join('\n');
    return `${pad}<body name="${san(b.name)}" pos="${v3(pos)}" quat="${quat(q)}">
${pad}  ${jointXML(j)}
${pad}  ${geomXML(b.visual?.geometry)}
${kids ? kids + '\n' : ''}${pad}</body>`;
  };

  const tree = roots.map((r) => bodyXML(r.id, 0)).join('\n');
  return `<?xml version="1.0"?>
<!-- Generated by TETROBOT -->
<mujoco model="${san(name)}">
  <compiler angle="radian"/>
  <worldbody>
${tree}
  </worldbody>
</mujoco>
`;
}
