/**
 * sdf.ts — export the model graph to SDF (Gazebo/Ignition's format).
 *
 * Like URDF, SDF is link+joint, but joints carry their pose and reference parent/child
 * by name inside a <model>. We reuse the same graph→tree reduction as the URDF exporter
 * (first joint per child = parent; extra joints noted). Node-testable (three + analysis,
 * relative imports for the math).
 */
import * as THREE from 'three';
import { bodyMass, inertiaTensor } from '../../../kinematics/analysis';
import type { Document } from '@/core/model/index';

const _q = new THREE.Quaternion();
const _e = new THREE.Euler();
const san = (s: any) => String(s ?? 'x').replace(/[^A-Za-z0-9_]/g, '_');
const n = (v: any) => (Math.abs(v) < 1e-9 ? '0' : (+v).toFixed(6));
function pose(p: any, quat: any) {
  _q.set(quat[0], quat[1], quat[2], quat[3]); _e.setFromQuaternion(_q, 'XYZ');
  return `${n(p[0])} ${n(p[1])} ${n(p[2])} ${n(_e.x)} ${n(_e.y)} ${n(_e.z)}`;
}

function geometryXML(g: any) {
  switch (g?.type) {
    case 'box': return `<box><size>${n((g.size ?? [1, 1, 1])[0])} ${n((g.size ?? [1, 1, 1])[1])} ${n((g.size ?? [1, 1, 1])[2])}</size></box>`;
    case 'sphere': return `<sphere><radius>${n(g.radius ?? 0.5)}</radius></sphere>`;
    case 'cylinder': case 'capsule': return `<cylinder><radius>${n(g.radius ?? 0.5)}</radius><length>${n(g.length ?? 1)}</length></cylinder>`;
    case 'mesh': return `<mesh><uri>meshes/${san(g.assetId ?? 'mesh')}.stl</uri></mesh>`;
    default: return `<box><size>0.1 0.1 0.1</size></box>`;
  }
}

function linkXML(body: any, doc: any, fkPose: string) {
  const g = body.visual?.geometry ?? {};
  const m = bodyMass(body, doc);
  const it = body.inertial && !body.inertial.auto ? body.inertial.inertia : inertiaTensor(g, body.transform?.scale, m);
  return `    <link name="${san(body.name)}">
      <pose>${fkPose}</pose>
      <inertial><mass>${n(m)}</mass>
        <inertia><ixx>${n(it.ixx)}</ixx><ixy>${n(it.ixy)}</ixy><ixz>${n(it.ixz)}</ixz><iyy>${n(it.iyy)}</iyy><iyz>${n(it.iyz)}</iyz><izz>${n(it.izz)}</izz></inertia>
      </inertial>
      <visual name="${san(body.name)}_v"><geometry>${geometryXML(g)}</geometry></visual>
      <collision name="${san(body.name)}_c"><geometry>${geometryXML(g)}</geometry></collision>
    </link>`;
}

function jointXML(j: any, doc: any) {
  const p = doc.bodies[j.parentBodyId], c = doc.bodies[j.childBodyId];
  const lim = j.limit ?? {};
  const type = j.type === 'continuous' ? 'revolute' : j.type === 'fixed' ? 'fixed' : j.type;
  const ax = j.axis ?? [0, 0, 1];
  const limXML = (j.type === 'revolute' || j.type === 'prismatic')
    ? `<limit><lower>${n(lim.lower ?? -3.14)}</lower><upper>${n(lim.upper ?? 3.14)}</upper><effort>${n(lim.effort ?? 0)}</effort><velocity>${n(lim.velocity ?? 0)}</velocity></limit>` : '';
  return `    <joint name="${san(j.name)}" type="${type}">
      <parent>${san(p.name)}</parent>
      <child>${san(c.name)}</child>
      <axis><xyz>${n(ax[0])} ${n(ax[1])} ${n(ax[2])}</xyz>${limXML}</axis>
    </joint>`;
}

export function exportSDF(doc: Document, name = 'tetrobot') {
  const bodies = Object.values(doc.bodies);
  const allJoints = Object.values(doc.joints);
  // graph→tree (first joint per child wins)
  const childParent = new Map<string, any>();
  const treeJoints: any[] = [];
  for (const j of allJoints) {
    const pid = (j as any).parentBodyId, cid = (j as any).childBodyId;
    if (!pid || !cid || !doc.bodies[pid] || !doc.bodies[cid]) continue;
    if (!childParent.has(cid)) { childParent.set(cid, j); treeJoints.push(j); }
  }
  // FK world poses for link <pose>
  // (lazy import avoided; analysis already pulls FK — but we compute here directly)
  const links = bodies.map((b) => {
    const t = b.transform ?? {}; return linkXML(b, doc, pose(t.position ?? [0, 0, 0], t.quaternion ?? [0, 0, 0, 1]));
  }).join('\n');
  const joints = treeJoints.map((j) => jointXML(j, doc)).join('\n');
  return `<?xml version="1.0"?>
<!-- Generated by TETROBOT -->
<sdf version="1.7">
  <model name="${san(name)}">
${links}
${joints}
  </model>
</sdf>
`;
}
