/**
 * urdf.js — export the model graph to URDF (the ROS robot format).
 *
 * URDF is a TREE: each link (except the root) has exactly one parent joint. Our
 * model is a graph, so we take the first joint per child as its parent (extra
 * joints = loop closures, emitted as comments) and pick a root (a body that is no
 * joint's child). Geometry, limits, dynamics, materials, and a rough inertial come
 * straight from the model. Mesh bodies reference meshes/<name> (export the STL
 * separately for now). Node-testable (only three + analysis, relative imports).
 */
import * as THREE from 'three';
import { bodyMass, inertiaTensor } from '../../../kinematics/analysis';
import type { Document } from '@/core/model/index';

const _q = new THREE.Quaternion();
const _e = new THREE.Euler();

const san = (s) => String(s ?? 'x').replace(/[^A-Za-z0-9_]/g, '_');
const n = (v) => (Math.abs(v) < 1e-9 ? '0' : (+v).toFixed(6));

function rpy(quat) {
  _q.set(quat[0], quat[1], quat[2], quat[3]);
  _e.setFromQuaternion(_q, 'XYZ');
  return `${n(_e.x)} ${n(_e.y)} ${n(_e.z)}`;
}
const xyz = (p) => `${n(p[0])} ${n(p[1])} ${n(p[2])}`;

function geometryXML(g) {
  switch (g?.type) {
    case 'box': return `<box size="${xyz(g.size ?? [1, 1, 1])}"/>`;
    case 'sphere': return `<sphere radius="${n(g.radius ?? 0.5)}"/>`;
    case 'cylinder': case 'capsule': return `<cylinder radius="${n(g.radius ?? 0.5)}" length="${n(g.length ?? 1)}"/>`;
    case 'mesh': return `<mesh filename="meshes/${san(g.assetId ?? 'mesh')}.stl"/>`;
    default: return `<box size="0.1 0.1 0.1"/>`;
  }
}

function linkXML(body, doc) {
  const g = body.visual?.geometry ?? {};
  const mat = body.visual?.materialId ? doc.materials[body.visual.materialId] : null;
  const m = bodyMass(body, doc);
  const it = body.inertial && !body.inertial.auto ? body.inertial.inertia
    : inertiaTensor(g, body.transform?.scale, m);
  const com = body.inertial?.com ?? [0, 0, 0];
  const matXML = mat
    ? `\n      <material name="${san(mat.name)}"><color rgba="${n(mat.color[0])} ${n(mat.color[1])} ${n(mat.color[2])} ${n(mat.color[3] ?? 1)}"/></material>`
    : '';
  return `  <link name="${san(body.name)}">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>${geometryXML(g)}</geometry>${matXML}
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>${geometryXML(g)}</geometry>
    </collision>
    <inertial>
      <origin xyz="${xyz(com)}" rpy="0 0 0"/>
      <mass value="${n(m)}"/>
      <inertia ixx="${n(it.ixx)}" ixy="${n(it.ixy)}" ixz="${n(it.ixz)}" iyy="${n(it.iyy)}" iyz="${n(it.iyz)}" izz="${n(it.izz)}"/>
    </inertial>
  </link>`;
}

function jointXML(j, doc) {
  const p = doc.bodies[j.parentBodyId], c = doc.bodies[j.childBodyId];
  const o = j.origin ?? { position: [0, 0, 0], quaternion: [0, 0, 0, 1] };
  const lim = j.limit ?? {};
  const needsLimit = j.type === 'revolute' || j.type === 'prismatic';
  const limXML = needsLimit
    ? `\n    <limit lower="${n(lim.lower ?? -3.14)}" upper="${n(lim.upper ?? 3.14)}" effort="${n(lim.effort ?? 0)}" velocity="${n(lim.velocity ?? 0)}"/>`
    : '';
  const dyn = j.dynamics ?? {};
  return `  <joint name="${san(j.name)}" type="${j.type}">
    <parent link="${san(p.name)}"/>
    <child link="${san(c.name)}"/>
    <origin xyz="${xyz(o.position)}" rpy="${rpy(o.quaternion)}"/>
    <axis xyz="${xyz(j.axis ?? [0, 0, 1])}"/>${limXML}
    <dynamics damping="${n(dyn.damping ?? 0)}" friction="${n(dyn.friction ?? 0)}"/>
  </joint>`;
}

export function exportURDF(doc: Document, name = 'tetrobot') {
  const bodies = Object.values(doc.bodies);
  const allJoints = Object.values(doc.joints);
  if (bodies.length === 0) return `<?xml version="1.0"?>\n<robot name="${san(name)}"/>\n`;

  // First joint per child = its parent; the rest are loop closures.
  const childParent = new Map();
  const treeJoints = [];
  const loopJoints = [];
  for (const j of allJoints) {
    if (!doc.bodies[j.parentBodyId] || !doc.bodies[j.childBodyId]) continue;
    if (childParent.has(j.childBodyId)) loopJoints.push(j);
    else { childParent.set(j.childBodyId, j); treeJoints.push(j); }
  }
  const roots = bodies.filter((b) => !childParent.has(b.id));

  const warns = [];
  if (roots.length > 1) warns.push(`Multiple roots (${roots.length}) — URDF needs one; first is the base.`);
  if (loopJoints.length) warns.push(`${loopJoints.length} loop joint(s) dropped: ${loopJoints.map((j) => san(j.name)).join(', ')}.`);

  const header = warns.length ? `  <!-- WARNINGS: ${warns.join(' ')} -->\n` : '';
  const links = bodies.map((b) => linkXML(b, doc)).join('\n');
  const joints = treeJoints.map((j) => jointXML(j, doc)).join('\n');

  return `<?xml version="1.0"?>
<!-- Generated by TETROBOT -->
<robot name="${san(name)}">
${header}${links}
${joints}
</robot>
`;
}